website mirroring

diff --git a/acorn-git-clone-website b/acorn-git-clone-website
--- a/acorn-git-clone-website
+++ b/acorn-git-clone-website
@@ -107,7 +107,11 @@ if [ -z "$(which git)" ]; then
 fi
 
 # -------------------------------------------- Main repo cloning
-git clone git@gitlab.acornassociated.org:$git_repo_group/$git_repo_name.git $install_dir/$git_repo_name
+git clone git@gitlab.acorn.org:$git_repo_group/$git_repo_name.git $install_dir/$git_repo_name
+if [ $? != 0 ]; then
+	echo "${RED}ERROR${NC}: Failed to clone ${YELLOW}$git_repo_group/$git_repo_name${NC}"
+	exit 1
+fi
 git config --global --add safe.directory $install_dir/$git_repo_name
 
 # -------------------------------------------- Apache and database
@@ -117,4 +121,11 @@ sudo $dir_script/acorn-setup-hostname
 # This is how I do permissions. Maybe there is a better way
 sudo chown -R www-data:www-data .
 sudo chmod -R g+rw .
+cd -
+
+# -------------------------------------------- Winter
+cd $install_dir/$git_repo_name
+./artisan winter:up
+composer install
+./artisan winter:passwd admin password
 cd -
