'no_message'

diff --git a/acorn-setup-laptop-from-usb b/acorn-setup-laptop-from-usb
--- a/acorn-setup-laptop-from-usb
+++ b/acorn-setup-laptop-from-usb
@@ -1,15 +1,20 @@
 #!/bin/bash
-
+################################
 RED="$(tput setaf 1)"
 GREEN="$(tput setaf 2)"
 YELLOW="$(tput setaf 3)"
 NC="$(tput sgr0)"
 TICK="${GREEN}✓${NC}"
 CROSS="${RED}✘${NC}"
+################################
 
 central_server=acorn.org
 git_server=gitlab.$central_server
+git_ip_address='192.168.88.252'
 download_dir=~/Downloads
+
+git_user="$1"
+if [ -z "$git_user" ]; then git_user="$USER"; fi
 
 # Pre-requisites
 # We assume network connectivity
@@ -22,22 +27,25 @@ if [ ! -d $download_dir ]; then
     if [ $? != 0 ]; then echo "${RED}ERROR${NC}: Cannot create $download_dir"; exit 1; fi
 fi
 
-if [ ! -f $download_dir/tor-browser/start-tor-browser ]; then
-    # Install and run tor
-    if [ -f acorn-setup-tor ]; then
-        # Often on FAT32 filesystems, so no +x
-        bash ./acorn-setup-tor
-        if [ $? != 0 ]; then exit 1; fi
-    else
-        echo "${RED}ERROR${NC}: Cannot find ${YELLOW}acorn-setup-tor${NC}"
-        exit 1
-    fi
-else
-    echo "Found tor-browser"
-fi
-cd $download_dir/tor-browser/
-bash start-tor-browser
-cd -
+# NOTE: Old tor-browser system for external access to our GitLab
+# if [ ! -f $download_dir/tor-browser/start-tor-browser ]; then
+#     # Install and run tor
+#     if [ -f acorn-setup-tor ]; then
+#         # Often on FAT32 filesystems, so no +x
+#         bash ./acorn-setup-tor
+#         if [ $? != 0 ]; then exit 1; fi
+#     else
+#         echo "${RED}ERROR${NC}: Cannot find ${YELLOW}acorn-setup-tor${NC}"
+#         exit 1
+#     fi
+# else
+#     echo "Found tor-browser"
+# fi
+# cd $download_dir/tor-browser/
+# bash start-tor-browser
+# cd -
+echo "${GREEN}INFO${NC}: Added $git_server in to /etc/hosts as ${YELLOW}$git_ip_address${NC}"
+echo "$git_ip_address $git_server" | sudo tee -a /etc/hosts
 
 # Setup the server git profile for pulls
 if [ ! -f ~/.ssh/id_rsa.pub ]; then
@@ -46,14 +54,14 @@ if [ ! -f ~/.ssh/id_rsa.pub ]; then
 fi
 echo "${GREEN}INFO${NC}: Pulic key:"
 cat ~/.ssh/id_rsa.pub
-echo "${GREEN}INFO${NC}: Add the user ${YELLOW}$USER${NC} to ${YELLOW}http://$git_server${NC}, with the above ssh key and password ${YELLOW}@corn.org${NC}"
+echo "${GREEN}INFO${NC}: Add the user ${YELLOW}$git_user${NC} to ${YELLOW}https://$git_server${NC}, with the above ssh key and password ${YELLOW}@corn.org${NC}"
 echo "And give Reporter access to ${YELLOW}office/scripts${NC} and any repositories you wish to pull"
-read -p "Done (Maybe needs tor-browser running)? " yn
+read -p "Done? " yn
 
 # Primary aim is to git clone scripts and pass control over
 if [ ! -d ~/scripts/.git ]; then
     # Detect if we need a proxy
-    wget -o $download_dir/test_git $git_server
+    wget -o $download_dir/test_git https://$git_server
     if [ $? != 0 ]; then
         echo "${RED}ERROR${NC}: Cannot access ${YELLOW}$git_server${NC}"
 
@@ -77,8 +85,8 @@ if [ ! -d ~/scripts/.git ]; then
 
     # GitLab connection
     if [ -z "$(git config --global user.name)" ]; then
-        git config --global user.name  $USER
-        git config --global user.email $USER@$central_server
+        git config --global user.name  $git_user
+        git config --global user.email $git_user@$central_server
     fi
 
     # Download latest acorn-setup-laptop
diff --git a/acorn-winter-update-sqls b/acorn-winter-update-sqls
--- a/acorn-winter-update-sqls
+++ b/acorn-winter-update-sqls
@@ -7,18 +7,51 @@ NC="$(tput sgr0)"
 TICK="${GREEN}✓${NC}"
 CROSS="${RED}✘${NC}"
 
+run_dir=`pwd` # Bald
+script_dir=`dirname $(realpath $0)`
+script=`basename $0`
+
 outfile=up.sql
 
 # -------------------------------------------- .env parse
 # Get DB connection parameters from Laravel
+# NOTE: This script can be run from several places:
+#   /var/www/<website> to update all SQL dumps
+#   ~/plugins/acorn/<plugin>/updates to update a specific SQL dump
+env='.env'
+if [ -f $env ] && [ -d plugins ]; then
+  # Batch run on whole website
+  for plugin in plugins/acorn/*/; do
+    if [ -f "$plugin/updates/$script" ]; then
+      read -p "${INFO}RUN${NC} ${YELLOW}$plugin${NC} (y|n)? [n] " yn
+      if [ "$yn" == 'y' ]; then
+        cd "$plugin/updates/"
+        ./$script
+        cd -
+      fi
+    fi
+  done
+  exit 0
+fi
+
+# Specific run
 env="../../../../.env"
-DB_CONNECTION=`grep DB_CONNECTION $env | cut -d '=' -f 2`
-DB_HOST=`grep DB_HOST $env | cut -d '=' -f 2`
-DB_PORT=`grep DB_PORT $env | cut -d '=' -f 2`
-DB_DATABASE=`grep DB_DATABASE $env | cut -d '=' -f 2`
-DB_USERNAME=`grep DB_USERNAME $env | cut -d '=' -f 2`
-DB_PASSWORD=`grep DB_PASSWORD $env | cut -d '=' -f 2`
+if [ ! -f $env ]; then
+  echo "${RED}ERROR${NC}: .env not found in document root"
+  exit 0
+fi
+
+DB_CONNECTION=`grep DB_CONNECTION $env | tr -d "'" | cut -d '=' -f 2`
+DB_HOST=`grep DB_HOST $env | tr -d "'" | cut -d '=' -f 2`
+DB_PORT=`grep DB_PORT $env | tr -d "'" | cut -d '=' -f 2`
+DB_DATABASE=`grep DB_DATABASE $env | tr -d "'" | cut -d '=' -f 2`
+DB_USERNAME=`grep DB_USERNAME $env | tr -d "'" | cut -d '=' -f 2`
+DB_PASSWORD=`grep DB_PASSWORD $env | tr -d "'" | cut -d '=' -f 2`
 echo "Dump Database: ${YELLOW}$DB_DATABASE${NC} with ${YELLOW}$DB_USERNAME${NC}/${YELLOW}$DB_PASSWORD${NC}"
+if [ "$DB_CONNECTION" != 'pgsql' ] || [ "$DB_HOST" != "127.0.0.1" ]; then
+  echo "${RED}$DB_CONNECTION@$DB_HOST:$DB_PORT${NC} is not local. Aborted"
+  exit 1
+fi
 
 # -------------------------------------------- Plugin parse
 dir=`pwd`
@@ -31,15 +64,35 @@ author_plugin="${author_name}_${plugin_name}"
 table_space="$schema.${author_plugin}_*"
 function_space="[^ ]*$author_plugin[a-z0-9_]+\([a-z0-9, ]*\)"
 echo "Author: ${YELLOW}$author_name${NC}, Plugin: ${YELLOW}$plugin_name${NC}, Tablespace: ${YELLOW}$table_space${NC}"
+if [ "$author_name" != 'acorn' ]; then
+  echo "${RED}$author_name${NC} is not ours. Aborted"
+  exit 1
+fi
 
 if [ -f $outfile ]; then rm $outfile; fi
+pg_dump -Fc -s $DB_DATABASE > dump.sql
 
 # -------------------------------------------- Up Functions
-IFS=$'\n' # Spaces in argument lists
-for f in `pg_dump -Fc -s $DB_DATABASE | pg_restore -l | grep -oE "^[0-9;]+ [0-9;]+ [0-9;]+ FUNCTION [a-z]+ $function_space" | cut -d ' ' -f 6,7,8,9,10,11,12`; do
+echo
+echo "${GREEN}Functions${NC} dump => ${YELLOW}$outfile${NC}"
+IFS=$'\n' # Avoid spaces in argument lists
+functions=`cat dump.sql | pg_restore -l | grep -oE "^[0-9;]+ [0-9;]+ [0-9;]+ FUNCTION [a-z]+ $function_space" | cut -d ' ' -f 6,7,8,9,10,11,12`
+for f in $functions; do
   echo "-- MANUAL FUNCTION DUMP $f" >> $outfile
   echo $f
-  pg_dump -Fc -s $DB_DATABASE | pg_restore --clean --if-exists --no-owner --no-privileges --format=c --function="$f" -f - >> $outfile
+  cat dump.sql | pg_restore --clean --if-exists --no-owner --no-privileges --format=c --function="$f" -f - >> $outfile
+done
+IFS=$' '
+
+# -------------------------------------------- Up Aggregates
+echo
+echo "${GREEN}Aggregates${NC} dump => ${YELLOW}$outfile${NC}"
+IFS=$'\n' # Avoid spaces in argument lists
+functions=`cat dump.sql | pg_restore -l | grep -oE "^[0-9;]+ [0-9;]+ [0-9;]+ AGGREGATE [a-z]+ $function_space" | cut -d ' ' -f 6,7,8,9,10,11,12`
+for f in $functions; do
+  echo "-- MANUAL AGGREGATE DUMP $f" >> $outfile
+  echo $f
+  cat dump.sql | pg_restore --clean --if-exists --no-owner --no-privileges --format=c --function="$f" -f - >> $outfile
 done
 IFS=$' '
 
@@ -47,17 +100,26 @@ IFS=$' '
 # Tables, Sequences and views
 #--username=$DB_USERNAME --password=$DB_PASSWORD \
 #--host=$DB_HOST --port=$DB_PORT \
-echo "Main DB dump"
-pg_dump --no-owner --schema-only --table="$table_space" --no-privileges --clean --if-exists --inserts --no-security-labels --no-subscriptions \
+echo
+echo "${GREEN}Main${NC} DB dump => ${YELLOW}$outfile${NC}"
+pg_dump --schema-only --table="$table_space" --clean --if-exists --no-owner --no-privileges --inserts --no-security-labels --no-subscriptions \
    $DB_DATABASE -f - >> $outfile
 
 # If we created new schemas then we need to reset
 echo "SET search_path TO public;" >> $outfile
 
+# -------------------------------------------- Show views
+echo "Views included:"
+grep -i "CREATE VIEW " $outfile | cut -d ' ' -f 3
+trigger_count=`grep -i "CREATE TRIGGER " $outfile | wc -l`
+echo "$trigger_count triggers"
+
 # -------------------------------------------- Down
-echo "All drops in to down.sql"
+echo
+echo "${GREEN}Drops${NC} in to => ${YELLOW}down.sql${NC}"
 if [ -f down.sql ]; then rm down.sql; fi
 grep -E "^ALTER TABLE IF EXISTS ONLY .* DROP CONSTRAINT .*" $outfile >> down.sql
-grep -E "^DROP.*" $outfile >> down.sql
+grep -E "^DROP .*" $outfile >> down.sql
 
+rm dump.sql
 echo "Done."
